name: Go Tests

on:
  push:
    branches:
      - main # Run tests when pushing to the main branch
    tags:
      - "v*" # Optional: Run tests when a version tag is pushed (e.g., v1.0.0)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      # Run tests
      - name: Run tests
        run: go test ./...
